/********************************************************************************
 * Constants
 * These are used to define Precise pages
 ********************************************************************************/

import { IParticipantForm } from "../stores";

/**
 * Schema where keys represent table ID and values represent form metadata
 * @param icon - Custom icons are placed in `src/assets/icons` and made available
 * by registering in src/app/components/icons.ts
 * @param mapFields - These refer to any additional data that should be passed from, formatted as:
 * ```
 * [{
 *     table_id: "my_table",
 *     field_name: "some_field",
 *     mapped_field_name: "some_other_field" (optional renaming),
 *  }]
 * ```
 * @remark - only supports a single subform for each table
 */
export const PRECISE_SCHEMA = {
  Birthbaby: {
    title: "Birth Baby",
    formId: "Birthbaby",
    tableId: "Birthbaby",
    icon: "baby",
    mapFields: [
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_date',
      },
      {table_id: 'Visit1',
        field_name: 'f6a_ultrasound3_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound3_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_lmp',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_as_sfh',
      },
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ga_enrol',
      },
      {table_id: 'Birthmother',
      field_name: 'f7_delivery_location',
      },
    ],
  },
  Birthmother: {
    title: "Birth Mother",
    formId: "Birthmother",
    tableId: "Birthmother",
    icon: "mother",
    mapFields: [
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_date',
      },
      {table_id: 'Visit1',
        field_name: 'f6a_ultrasound3_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound3_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_lmp',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_as_sfh',
      },
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ga_enrol',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_fgr_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_hypertension_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_stillbirth_cohort',
      },
      {table_id: 'Visit2',
      field_name: 'f6a2_tod_fgr_cohort',
      },
      {table_id: 'Visit2',
      field_name: 'f6a2_tod_hypertension_cohort',
      },
      {table_id: 'Visit2',
      field_name: 'f6a2_tod_stillbirth_cohort',
      },
    ],
  },
  profileSummary: {
    title: "General Info",
    formId: "profileSummary",
    tableId: "profileSummary",
    icon: "profile",
  },
  profileSummaryRevisions: {
    title: "General Info Revisions",
    formId: "profileSummaryRevisions",
    tableId: "profileSummaryRevisions",
    icon: "history",
  },
  Lab: {
    title: "Laboratory",
    formId: "Lab",
    tableId: "Lab",
    icon: "lab",
    allowRepeats: true,
    mapFields: [
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_date',
      },
      {table_id: 'Visit1',
        field_name: 'f6a_ultrasound3_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound3_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_lmp',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_as_sfh',
      },
    ],
  },
  Postpartum_baby: {
    title: "Postpartum Baby",
    formId: "Postpartum_baby",
    tableId: "Postpartum_baby",
    icon: "baby",
    mapFields: [
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
    ],
  },
  Postpartum_mother: {
    title: "Postpartum Mother",
    formId: "Postpartum_mother",
    tableId: "Postpartum_mother",
    icon: "mother",
    mapFields: [
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_date',
      },
      {table_id: 'Visit1',
        field_name: 'f6a_ultrasound3_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound3_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_lmp',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_as_sfh',
      },
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ga_enrol',
      },
    ],
    
  },
  screening: {
    title: "Participant Screening",
    formId: "screening",
    tableId: "screening",
    icon: "screen",
  },
  TOD_ANC: {
    title: "ToD at ANC",
    formId: "TOD_ANC",
    tableId: "TOD_ANC",
    icon: "disease",
    allowRepeats: true,
    mapFields: [
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_date',
      },
      {table_id: 'Visit1',
        field_name: 'f6a_ultrasound3_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound3_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_lmp',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_as_sfh',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_fgr_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_hypertension_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_stillbirth_cohort',
      },
      {table_id: 'Visit2',
      field_name: 'f6a2_tod_fgr_cohort',
      },
      {table_id: 'Visit2',
      field_name: 'f6a2_tod_hypertension_cohort',
      },
    ],
  },
  Visit1: {
    title: "Precise Visit 1",
    formId: "Visit1",
    tableId: "Visit1",
    icon: "visit",
    mapFields: [
      {table_id: 'profileSummary',
      field_name: 'f2a_cohort',
    },
    ],
  },
  Visit2: {
    title: "Precise Visit 2",
    formId: "Visit2",
    tableId: "Visit2",
    icon: "visit",
    mapFields: [
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_date',
      },
      {table_id: 'Visit1',
        field_name: 'f6a_ultrasound3_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound1_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound2_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ultrasound3_edd_date',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_lmp',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_as_sfh',
      },
      {table_id: 'profileSummary',
        field_name: 'f2a_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_ga_enrol',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_fgr_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_hypertension_cohort',
      },
      {table_id: 'Visit1',
      field_name: 'f6a_tod_stillbirth_cohort',
      },
    ],
  },
  Withdrawal: {
    title: "Withdraw Participant",
    formId: "Withdrawal",
    tableId: "Withdrawal",
    icon: "",
    mapFields: [
      {table_id: 'profileSummary',
      field_name: 'f2a_cohort',
    },
    ],
  },
};

// Fields displayed in the profile under the 'summary' tab
export const PRECISE_SUMMARY_FIELDS = [
  {
    table: "Visit1",
    field: "f2_visit_date",
    label: "visit1_date",
  },
  {
    table: "Visit2",
    field: "f2_visit_date",
    label: "visit2_date",
  },
  {
    table: "Visit1",
    field: "f6a_ga_enrol",
    label: "visit1_ga",
  },
  {
    table: "Visit2",
    field: "f2_ga_at_visit",
    label: "visit2_ga",
  },
  {
    table: "Birthbaby",
    field: "f9_ga_at_delivery",
    label: "birth_ga",
  },
  {
    table: "Birthbaby",
    field: "f9_delivery_date",
    label: "delivery_date",
  },
  {
    table: "Birthbaby",
    field: "f7_delivery_num_of_babies",
    label: "number_of_babies",
  },
  {
    table: "Withdrawal",
    field: "fw_lost_to_followup",
    label: "LTF",
  },
  {
    table: "Withdrawal",
    field: "fw_withdraw_from_study",
    label: "withdrawal",
  },
];
/**
 * Sections shown on front participant page
 */
export const PRECISE_FORM_SECTIONS: IPreciseFormSection[] = [
  {
    icon: "visit",
    label: "Precise Visit",
    formIds: ["Visit1", "Visit2", "Birthmother", "Postpartum_mother"],
  },
  {
    icon: "disease",
    label: "TOD - ANC",
    formIds: ["TOD_ANC"],
  },
  {
    icon: "lab",
    label: "Lab",
    formIds: ["Lab"],
  },
];
/**
 * Subsection created for every new baby registered
 */
export const PRECISE_BABY_FORM_SECTION: IPreciseFormSection = {
  icon: "baby",
  label: "Baby",
  formIds: ["Birthbaby", "Postpartum_baby"],
};

/********************************************************************************
 * Types
 * These are used to ensure constants defined above are consistently formatted
 ********************************************************************************/
type IPreciseFormId = keyof typeof PRECISE_SCHEMA;

export interface IPreciseFormSection {
  // id purely used to later allow adjusting baby form section
  _id?: string;
  icon: string;
  label: string;
  formIds: IPreciseFormId[];
}

export interface ISectionWithMeta extends IPreciseFormSection {
  forms: IParticipantForm[];
}
